### ISSUE TITLE
Hugo's DisableRSS should be used instead of EnableRSS

### ISSUE THREAD

**Issue by mjbshaw** [digitalcraftsman/hugo-cactus-theme#1]
[`EnableRSS`](https://github.com/digitalcraftsman/hugo-cactus-theme/search?utf8=%E2%9C%93&q=EnableRSS) is used in this theme, but the Hugo uses [`DisableRSS`](https://github.com/spf13/hugo/search?utf8=%E2%9C%93&q=disablerss&type=Code). This means the site configuration file can set both flags individually, which is awkward (and can lead to errors, like if both are true or false).

Ideally this theme would use Hugo's variable (`DisableRSS`) instead of introducing a new alternative.

<sup>(And thanks for the nice port of the Cactus theme!)</sup>

**Comment by digitalcraftsman** [comment]
As it turned out, not all config parameters are accessable inside a template, which includes `DisableRSS`. You can find further information in [this forum post](http://discuss.gohugo.io/t/how-to-access-disablerss-param-in-templates/1476).

**Comment by mjbshaw** [comment]
Dang, you're right. Even trying `{{ if .RSSlink }}` like [the docs show](http://gohugo.io/templates/rss/) doesn't seem to work. `.RSSlink` seems to be present even if `DisableRSS` is set to true.

Well, in that case, you can close this issue if you like, seeing as this is a deficiency of Hugo and not the theme.

<sup>(Thanks for checking this out!)</sup>

**Comment by digitalcraftsman** [comment]
I agree with you that the use of both variables can be confusing, but I'll close the docs for now, since this seems to be a neccessary workaround. However, I'll have a look on this and asked in the forum post, if there are specific reasons for not making the configuration options accessible.
