### ISSUE TITLE
Awesome Fonts?

### ISSUE THREAD

**Issue by sidewinder12s** [digitalcraftsman/hugo-cactus-theme#10]
Hey how hard would it be to switch the using Awesome Fonts for the various links/social icons? It has a lot more available. The github icon in mono in particular is pretty bad, I thought it was for Google.

**Comment by digitalcraftsman** [comment]
Hello @sidewinder12s,

are you just talking about the icons in the footer? After looking at the GitHub logo I agree that it coule be Google's. I added an option to the config file that allows you to switch between Fontawesome and the default Mono social icon font.

[Here](https://github.com/digitalcraftsman/hugo-cactus-theme/commit/79e5435d6be25ae882ab5ae8455f17834f109a32) you can find the corresponding instructions.

**Comment by sidewinder12s** [comment]
Yup, those were the primary icons I was talking about. 

Thanks for the quick response/resolution!
