### ISSUE TITLE
Idea for feature

### ISSUE THREAD

**Issue by rrampr-zz** [digitalcraftsman/hugo-cactus-theme#11]
Pagination: The homepage could have a long list of posts, and pagination would help with faster loads
Tags: Adding tags to each post would allow you to see the list of posts with a particular tag.

**Comment by digitalcraftsman** [comment]
Hello @rrampr,

pagination should work out the box. Hugo paginates by default only if you have more then 10 content files that are rendered. You can change this behavior in the config file with the `paginate` variable.

Tags would be an addition of my own to this port but I'll see what I can do to add them.

**Comment by digitalcraftsman** [comment]
I added a the tags as list below the header. Pull the latest additions and you're ready to go.

Cheers,
Digitalcraftsman
