### ISSUE TITLE
Ordered lists not properly rendered

### ISSUE THREAD

**Issue by pawanrawal** [digitalcraftsman/hugo-cactus-theme#12]
Not sure if this is a problem with the theme or I am missing something. But when I add something like
1. First para
2. Second Para

they are rendered as unordered lists instead of ordered lists. Could you point me to what I might be doing wrong here ?

**Comment by digitalcraftsman** [comment]
Hello @paranrawal,

could you give an example, where wich parameters are shown in a wrong order?

**Comment by pawanrawal** [comment]
Its just that ordered lists are shown as unordered.

So
1. First para
2. Second para

is shown as
- First para
- Second para

**Comment by jmhickman** [comment]
I think this is actually an issue with BlackFriday, and not this theme.

**Comment by digitalcraftsman** [comment]
@pawanrawal it's not an issue with BlackFriday. A [CSS rule](https://github.com/digitalcraftsman/hugo-cactus-theme/blob/master/static/css/style.css#L186) causes the behavior.

Every list-item (`<li>`) will be rendered as a circle. It doesn't matter if it is wrapped in a ordered or unordered list.

**Comment by sudoforge** [comment]
Shouldn't this be closed?
