### ISSUE TITLE
Google logo shows up in place of Github

### ISSUE THREAD

**Issue by pawanrawal** [digitalcraftsman/hugo-cactus-theme#13]
On the homepage , Google logo shows up instead of the Github logo for the GitHub social link.

**Comment by digitalcraftsman** [comment]
Hello @pawanrawal,

the "Google" icon is the correct icon for GitHub. I had a similar discussion in #10 and I agree that the icon is ambiguous. But you use FontAwesome as an alternative if you like. The config option is documented in the README.

Cheers,
Digitalcraftsman

**Comment by rudedogg** [comment]
Using `githubalt = "username"` instead of `github = "username"` in the `[social]` block of `config.toml` gives you the :octocat: icon. 

Seems odd, but it works with how the template is coded 👍 .
