### ISSUE TITLE
Cactus does not render inline `code`

### ISSUE THREAD

**Issue by weitzj** [digitalcraftsman/hugo-cactus-theme#14]
I really like this Theme. One thing holding me back is missing support for `inline code`.

Any hints, how I could fix this?

**Comment by weitzj** [comment]
It seems to work, if I change:

`span.code { font-family:Menlo, Monaco, Courier; background-color:#EEE; font-size:14px; }`

to

`code { font-family:Menlo, Monaco, Courier; background-color:#EEE; font-size:14px; }`

**Comment by digitalcraftsman** [comment]
Hello @weitzj,

you already spotted the issue in the right place. In 7921c05d7e32df62f43b0df46b501f455182e290 I extended the stylesheet for a better highlighting of inline code examples.

Let me know if this addition works for you.

Cheers, 
Digitalcraftsman

**Comment by weitzj** [comment]
👍
