### ISSUE TITLE
404 does not get redirected

### ISSUE THREAD

**Issue by calvn** [digitalcraftsman/hugo-cactus-theme#15]
It seems that 404.html does not seem to get redirected on 404's. For example, if I don't have an about page, the browser does not redirect to 404.html, but instead gives me a generic `404 - page not found` for that particular URL.

**Comment by calvn** [comment]
Actually, this might be an issue with `hugo server` and not with the template. https://gohugo.io/templates/404/ explains how 404's are handled depending on host.

**Comment by digitalcraftsman** [comment]
Hello @cleung2010,

this behavior is caused be Hugo's built-in server that doesn't handle 404 errors. It just a simple file server. The 404 page needs to be accessed manually. See spf13/hugo#874
