### ISSUE TITLE
Demo on theme site is broken

### ISSUE THREAD

**Issue by aerohub** [digitalcraftsman/hugo-cactus-theme#17]

**Comment by digitalcraftsman** [comment]
Hello @aerohub,

to what url are you referring?

**Comment by aerohub** [comment]
Well, i told about this one. It went to unstyled demo. But now it is okay, sorry
![00003](https://cloud.githubusercontent.com/assets/16353578/19619001/e47c9bd8-9863-11e6-875e-2c56609d2c7b.png)

**Comment by digitalcraftsman** [comment]
> Well, i told about this one. It went to unstyled demo. But now it is okay, sorry

I thought some link would be broken according to the issue title and tested all of them. However, what do you mean with "It went to unstyled demo"?

I'm sorry if I miss anything :smile:

**Comment by aerohub** [comment]
It was this way:
- I clicked on link in repo description
- And this was opened

![00004](https://cloud.githubusercontent.com/assets/16353578/19619141/3a199222-9868-11e6-92c8-cafcfdbc9e91.png)

**Comment by digitalcraftsman** [comment]
Ok, the demo on the theme site is broken. Thanks for reporting this issue :+1: 
I'll investigate what causes the issue.

**Comment by aerohub** [comment]
Ok, glad to help)

**Comment by digitalcraftsman** [comment]
I'm closing this issue since the demo is working fine via https.
