### ISSUE TITLE
Open Graph Tags 

### ISSUE THREAD

**Issue by qwo** [digitalcraftsman/hugo-cactus-theme#19]
It would be nice to have pretty previews specified through  frontmatter for each blog post. 

Would it be something the theme would be interested in? It can also gracefully fallback to normal defaults if it's not specified in the frontmatter such as it is now. 

I was thinking about working on this and was wondering if it was a welcomed upstream contribution.

**Comment by digitalcraftsman** [comment]
Hello @stanzheng,

Hugo already ships templates to support OpenGraph, Google News and Twitter cards. I added them in 7252f59950d868f936ff3cb088ad5c183e53a266. So far they aren't documented (see spf13/hugo#1727).

However, their implementation was [discussed in the Hugo forum](https://discuss.gohugo.io/t/hugo-seo-social-partials/353). The second part of the discussion should reflect the usage.

**Comment by qwo** [comment]
Awesome. Thanks @digitalcraftsman!
