### ISSUE TITLE
Same section IDs in profile.html and index.html

### ISSUE THREAD

**Issue by primoz-k** [digitalcraftsman/hugo-cactus-theme#21]
I think there is a problem with multiple sections that have the same ID: `wrapper`.

Example: 
`profile.html` : https://github.com/digitalcraftsman/hugo-cactus-theme/blob/master/layouts/partials/profile.html#L2

`index.html` : https://github.com/digitalcraftsman/hugo-cactus-theme/blob/master/layouts/index.html#L7

`profile.html` is included in `index.html` as a partial. Am I correct or missing something?

**Comment by digitalcraftsman** [comment]
Hello @primoz-k,

could you elaborate a bit further what your issue you see?

Cheers,
Digitalcraftsman

**Comment by primoz-k** [comment]
Hi!

I guess the problem disappeared when you refactored this theme.
Before refactor, the compiled index.html had multiple sections/divs with the same ID.

I can not reproduce that bug now, so I guess you fixed it in the process of refactoring. :)

Closing now, thank you for your work!
