### ISSUE TITLE
Google Analytics Tracking code

### ISSUE THREAD

**Issue by dlogvinenko** [digitalcraftsman/hugo-cactus-theme#3]
Would be nice to add Google Analytics Tracking code feature.

**Comment by dlogvinenko** [comment]
@digitalcraftsman that was fast! :) Good job

**Comment by digitalcraftsman** [comment]
Added. You'll find a variable called `googleAnalytics` in `exampleSite/config.toml`. Enter your tracking code and you're ready to go.
