### ISSUE TITLE
Numbered lists?

### ISSUE THREAD

**Issue by podiki** [digitalcraftsman/hugo-cactus-theme#34]
This theme doesn't seem to support numbered lists, but uses the same bullet for all lists. Is this a bug or a design decision?

**Comment by podiki** [comment]
Basic fix that works for me (at least in a simple test, decimal style):

In `static/css/style.css`
```
ul      { margin:0; padding:0; margin-bottom: 20px; list-style-type:circle}
ol      { list-style: decimal; }
li      { list-style-position:inside; }
```

In other words, move `list-style-type:circle` to `ul` from `li`, and add the `ol` style.

EDIT: Actually I'm not sure if that works (sorry, I have customized this theme, so I'm not sure what affected what). Simply adding
```
ol li      { list-style-type:decimal;}
```
to the style sheet (i.e. in a custom css included using the `config.toml`) does the trick.

**Comment by redfish-lee** [comment]
Is the bulleted sub-list in mardown work?

**Comment by digitalcraftsman** [comment]
> This theme doesn't seem to support numbered lists, but uses the same bullet for all lists. Is this a bug or a design decision?

It was a design decision by the original theme creator(s). 

#40 should fix this issue thanks to @jacobwarduk.

**Comment by digitalcraftsman** [comment]
> Is the bulleted sub-list in mardown work?

@redfish-lee for Markdown related questions please look at a Markdown reference guide.

**Comment by podiki** [comment]
Nice, thanks @jacobwarduk!
