### ISSUE TITLE
font-awesome.min.css

### ISSUE THREAD

**Issue by podiki** [digitalcraftsman/hugo-cactus-theme#35]
Looks like merging the `dev` branch erased a previous change to `layouts/partials/head.html` for loading Font Awesome from a CDN (issue #23). Since the local copy of Font Awesome is gone now, the font will not load. Hopefully no other changes that should have been kept were overwritten.

**Comment by codeblooded** [comment]
I'm having this same issue.

**Comment by podiki** [comment]
@codeblooded You can use the `head.html` in the linked issue to override the current one and it will work until the change is merged back in.

**Comment by codeblooded** [comment]
Ok! Great! Thanks @podiki !

**Comment by digitalcraftsman** [comment]
Hello @podiki,

thanks for reporting this issue.

> Looks like merging the dev branch erased a previous change to layouts/partials/head.html for loading Font Awesome from a CDN

This is correct that the CDN url was removed by accident during the merge.

Cheers,
Digitalcraftsman
