### ISSUE TITLE
Alternatives to `hidden: true`

### ISSUE THREAD

**Issue by couto** [digitalcraftsman/hugo-cactus-theme#57]
Im a newbie to Hugo, so there might be a way to do this that I'm missing.

According to the `exampleSite,` we could use `hidden: true` to hide posts from the post-list.
According to the CHANGELOG.md, `hidden: true` was deprecated in favor of `draft: true`. 

However `draft: true` is not equivalent to `hidden: true`, because the only way I can link to a draft page, is by enabling `--buildDrafts` and as soon as I do it, all drafts are listed on the post-list.

My use case, is that I have several pages in the about section, but they are not really posts, and should not be displayed in the post-list.

```
├── config.toml
├── content
│   ├── about
│   │   ├── _index.md
│   │   ├── page-1.md
│   │   └── page-2.md
│   └── post
│       └── post-1.md
```

My question is, how can I hide the `about/page-1.md` and `about/page-2.md` from the post-list, without `hidden: true` and still be able to link to those pages, and keep draft posts unlisted?

**Comment by jonasvp** [comment]
Did you find a solution for this? I have the same problem.

**Comment by couto** [comment]
@jonasvp I didn't. I just gave up on Hugo to be honest :\

**Comment by jonasvp** [comment]
Ah, good to know - thanks anyway for the quick feedback!
