### ISSUE TITLE
Theme seems broken

### ISSUE THREAD

**Issue by coussej** [digitalcraftsman/hugo-cactus-theme#7]
Hi, 

First off all thanks for the port of this theme, I really like its minimal design. However, the it seems to be broken for some reason. Even when you go to the [demo site](http://themes.gohugo.io/theme/cactus/), all views are broken. In the main screen, the image is too big and the about link is rendered in the top left corner. When you go to a post, the content stretches to the whole screen, and all paragraphs are rendered as a link. Screen shots below. I get the exact same result when I render a page of my blog. Tried in both safari as in chrome.

Thanks! 

![screen shot 2016-01-02 at 21 49 15](https://cloud.githubusercontent.com/assets/9944663/12076054/eac66006-b19a-11e5-9b0e-4ece8db931a4.png)

![screen shot 2016-01-02 at 21 49 35](https://cloud.githubusercontent.com/assets/9944663/12076053/eac53ed8-b19a-11e5-8c29-c2fd9f40b055.png)

**Comment by coussej** [comment]
Seems to be related to the addition of RSSLink to the site info. Was using a slightly outdated version of Hugo. Updated to latest and it worked. Demosite should still be fixed though.

**Comment by digitalcraftsman** [comment]
Hello @coussej,

thanks for opening this issue. With the latest release of Hugo 0.15 I refactored the theme.
However, the demo page should be updated. The last built date was December the 16th and maybe interfered with the refactoring.
