### ISSUE TITLE
Suppress pages from front page

### ISSUE THREAD

**Issue by jmhickman** [digitalcraftsman/hugo-cactus-theme#9]
Hi, I really like your theme, but I'm trying to find a way for a post to _not_ show up on the front page.

I basically want hugo to generate the page/post, but I need to link to it specifically from elsewhere and not have them clog up the "main" blog and front page where they don't make sense. 

Is there a way to do this? If not, is there a simple way it could be added? A parameter in the front matter like "hidden" or "suppressed" or something seems like it would work well.

I'm using your Agency theme and like it a lot. Your documentation is much much clearer than many other hugo themes, and your example sites tell me what I need to know to get things working. Thank you.

**Comment by digitalcraftsman** [comment]
Hi @jmhickman,

as in your proposal just add `hidden = true` as parameter to the frontmatter. Pull the lastest version and you're ready to go.

I appreciate your positive feedback. Thanks.

Cheers,
Digitalcraftsman

**Comment by jmhickman** [comment]
Perfect. Thank you so much!
